theme: jekyll-theme-dinky

integration_spreadsheet_key: 2PACX-1vSSq7rGVuEnA4NGENTx6SHRulCjBm9rzWpSXyi2Lv1-VtJqjJV0wdScAsXozNYRWGDtiYrMwgyOqogs

github_user: nelsonph87
github_repo: nelsonph87.github.io
